# Generated by Django 5.2.11 on 2026-02-19 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=128, unique=True)),
                ('patient_id', models.CharField(blank=True, max_length=128, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('FAILED', 'Failed'), ('READY', 'Ready')], default='PROCESSING', max_length=16)),
                ('progress', models.IntegerField(default=0)),
                ('status_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'queued'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='queued', max_length=16)),
                ('message', models.TextField(blank=True, null=True)),
                ('progress', models.IntegerField(default=0)),
                ('output_dir', models.CharField(blank=True, max_length=512, null=True)),
                ('rq_job_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='api.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('fat', 'fat'), ('fat_fraction', 'fat_fraction')], max_length=32)),
                ('filename', models.CharField(max_length=512)),
                ('file_path', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='api.case')),
            ],
        ),
    ]
